apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: demo-cypress-template
objects:

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: demo-cypress
  spec:
    lookupPolicy:
      local: true

- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: demo-cypress
    name: demo-cypress
  spec:
    source:
      contextDir: test
      git:
        ref: master
        uri: https://github.com/gary-jipp/demo-openshift-cypress
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: "cypress-docker:latest"
    output:
      to:
        kind: ImageStreamTag
        name: demo-cypress:latest

- kind: Deployment
  apiVersion: apps/v1
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"demo-cypress:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"demo-cypress\")].image"}]'
    name: demo-cypress
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: demo-cypress
    template:
      metadata:
        labels:
          deployment: demo-cypress
      spec:
        containers:
          - name: demo-cypress
            image: 'demo-cypress'
        restartPolicy: Always
