name: demo-cypress build
on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**/*.md'
      - '_openshift'
  workflow_dispatch:
defaults:
  run:
    working-directory: ./app
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Unit tests
        run: npm run test --if-present
  openshift-build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: OpenShift Build
        env:
          NAMESPACE: ${{ secrets.OpenShiftNamespace }}
          BUILD_NAME: demo-app
          IMAGE_NAME: demo-app
        uses: redhat-developer/openshift-actions@v1.1
        with:
          version: "latest"
          openshift_server_url: ${{ secrets.OpenShiftServerURL}}
          parameters: '{"apitoken": "${{ secrets.OpenShiftToken }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            'version'
            'start-build ${BUILD_NAME}  --follow'
# 'tag -n ${NAMESPACE} ${NAMESPACE}/${IMAGE_NAME}:latest ${NAMESPACE}/${IMAGE_NAME}:dev'
